// pages/terms.js
import styles from "../styles/LegalPage.module.css";

const sections = [
  {
    title: "Acceptance of Terms",
    content:
      "By accessing or using Sarjan AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform. Your continued use of the service constitutes your acceptance of any updates to these terms.",
  },
  {
    title: "Use of Service",
    content:
      "You may use Sarjan AI only for lawful purposes and in accordance with these terms. You agree not to use our platform in any way that violates applicable laws, infringes on intellectual property rights, or transmits harmful or offensive content.",
  },
  {
    title: "User Accounts",
    content:
      "When you create an account, you must provide accurate and complete information. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.",
  },
  {
    title: "Intellectual Property",
    content:
      "The platform and its original content, features, and functionality are and will remain the exclusive property of Sarjan AI. Our trademarks may not be used in connection with any product or service without prior written consent.",
  },
  {
    title: "AI-Generated Content",
    content:
      "Content generated by Sarjan AI is provided for your use subject to these terms. You retain ownership of the inputs you provide. You are solely responsible for how you use, publish, or distribute AI-generated outputs.",
  },
  {
    title: "Limitation of Liability",
    content:
      "Sarjan AI shall not be liable for any indirect, incidental, special, or consequential damages resulting from your use of or inability to use the service, even if we have been advised of the possibility of such damages.",
  },
  {
    title: "Termination",
    content:
      "We may terminate or suspend your account immediately, without prior notice, for conduct that we believe violates these Terms of Service or is harmful to other users, us, or third parties, or for any other reason at our sole discretion.",
  },
  {
    title: "Governing Law",
    content:
      "These terms shall be governed by and construed in accordance with applicable laws. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts in our registered jurisdiction.",
  },
];

export default function TermsOfService() {
  return (
    <main className={styles.wrapper}>
      <div className={styles.orb1} />
      <div className={styles.orb2} />

      <div className={styles.container}>
        <header className={styles.header}>
          <span className={styles.label}>LEGAL</span>
          <h1>Terms of Service</h1>
          <p>Last updated: January 1, 2025</p>
          <p className={styles.intro}>
            Please read these terms carefully before using Sarjan AI. By using
            our platform you agree to be bound by these terms.
          </p>
        </header>

        <div className={styles.sections}>
          {sections.map((sec, i) => (
            <div key={i} className={styles.card}>
              <div className={styles.cardGlow} />
              <div className={styles.cardNumber}>0{i + 1}</div>
              <h2>{sec.title}</h2>
              <p>{sec.content}</p>
            </div>
          ))}
        </div>

        <div className={styles.backRow}>
          <a href="/" className={styles.backLink}>← Back to Home</a>
        </div>
      </div>
    </main>
  );
}